# Generated by Django 4.2.7 on 2023-12-03 15:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0010_uploadmodel'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='imageUrl',
        ),
        migrations.AddField(
            model_name='product',
            name='image',
            field=models.FileField(default='', upload_to='images'),
        ),
    ]
